lobby:
  event-name: "The Journey"
  spawn:
    x: 0
    y: 150
    z: 0
  sign: "[The Journey]"
  first-universe: "SKY_LAND"
  welcome-message: "Welcome to The Journey event !"
  how-to-back: "To resume your game, click on the sign."
  event-start-in: "This event start in: <REAMING>."
  event-finished: "This event is finish !"
#

data:
  mongo:
    databases: ["master", "event_journey"]
    host: "127.0.0.1"
    port: 27017
    user: "minecraft"
    password: "admin"
    db: "admin"
#